# Generated by Django 4.2.5 on 2023-09-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=20)),
                ('harga', models.IntegerField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kriteria', models.CharField(max_length=50)),
                ('atribut', models.CharField(max_length=50)),
                ('bobot', models.FloatField()),
                ('pertanyaan', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subkriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_subkriteria', models.CharField(max_length=50)),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.kriteria')),
            ],
        ),
        migrations.CreateModel(
            name='Saw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
                ('subkriteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subkriteria')),
            ],
        ),
    ]
