# Generated by Django 3.2.22 on 2023-10-22 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=20)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField(default='')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('stok', models.CharField(default='tidak tersedia', max_length=20)),
                ('nilai', models.IntegerField(default=0)),
                ('jumlah_bintang', models.IntegerField(default=0)),
                ('jumlah_penilai', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kriteria', models.CharField(max_length=50)),
                ('atribut', models.CharField(max_length=50)),
                ('bobot', models.FloatField()),
                ('pertanyaan', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pemesanan', models.DateTimeField(auto_now=True)),
                ('total_pembayaran', models.IntegerField(default=0)),
                ('is_notified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('keranjang', 'Keranjang'), ('dikonfirmasi', 'Dikonfirmasi'), ('selesai', 'Selesai')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subkriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_subkriteria', models.CharField(max_length=50)),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.kriteria')),
            ],
        ),
        migrations.CreateModel(
            name='Saw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
                ('subkriteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subkriteria')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField(default='')),
                ('jumlah_pesanan', models.IntegerField(default=0)),
                ('total_harga', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
