# Generated by Django 3.2.22 on 2023-10-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
