# Generated by Django 4.2.5 on 2023-09-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_is_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jumlah_bintang',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='jumlah_penilai',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='nilai',
            field=models.IntegerField(default=0),
        ),
    ]
