# Generated by Django 4.2.6 on 2023-10-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_nama_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('menunggu_konfirmasi', 'Menunggu Konfirmasi'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_pembayaran',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='waktu_pemesanan',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='jumlah_pesanan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_harga',
            field=models.IntegerField(default=0),
        ),
    ]
