# Generated by Django 3.2.22 on 2023-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_order_qr_code_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('keranjang', 'Keranjang'), ('dikonfirmasi', 'Dikonfirmasi'), ('selesai', 'Selesai')], max_length=20),
        ),
    ]
