# Generated by Django 4.2.5 on 2023-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_item_jumlah_bintang_alter_item_jumlah_penilai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stok',
            field=models.CharField(default='Tidak tersedia', max_length=20),
        ),
    ]
