# Generated by Django 4.2.5 on 2023-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_item_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stok',
            field=models.CharField(default='tidak tersedia', max_length=20),
        ),
    ]
