# Generated by Django 3.2.22 on 2023-10-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20231018_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deskripsi',
            field=models.TextField(default=''),
        ),
    ]
