# Generated by Django 3.2.22 on 2023-10-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_notifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
